package com.example.yearend.deduction.domain;

public enum DeductionType {
    EARNED_INCOME_DEDUCTION,
    INCOME_TAX,
    PERSONAL_DEDUCTION,
    PENSION_INSURANCE_PREMIUM,
    SOCIAL_INSURANCE_PREMIUM,
    MEDICAL_EXPENSE,
    EDUCATION_EXPENSE,
    INSURANCE,
    DONATION,
    CREDIT_CARD
}
