package com.example.yearend.deduction.domain;

public enum DeductionType {
    EARNED_INCOME_DEDUCTION,
    INCOME_TAX,
    PERSONAL_DEDUCTION,
    PENSION_INSURANCE_PREMIUM,
    SOCIAL_INSURANCE_PREMIUM,
    MEDICAL_EXPENSE,
    EDUCATION_EXPENSE,
    INSURANCE,
    DONATION,
    CREDIT_CARD,
    CHILD_TAX_CREDIT,
    PENSION_ACCOUNT,
    MONTHLY_RENT,
    HOUSING_LOAN,
    LONG_TERM_MORTGAGE,
    HOUSING_SAVINGS,
    STANDARD_TAX_CREDIT,
    LONG_TERM_COLLECTIVE_INVESTMENT,
    YOUTH_LONG_TERM_COLLECTIVE_INVESTMENT,
    SME_MUTUAL_AID
}
